version: "3.4"
services:
  nopcommerce_web:
    build: .
    container_name: nopcommerce
    ports:
      - "80:80"
    depends_on:
      - nopcommerce_database
    volumes:
      - nopsettings:/app
  nopcommerce_database:
    image: "mysql:latest"
    container_name: nopcommerce_mysql_server
    command: "--default-authentication-plugin=mysql_native_password"
    restart: "always"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "lasenkimesikiyon10"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
  nopsettings:
